version: '3.9'

services:

  postgres:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: kickoff
      POSTGRES_HOST: localhost
    ports:
      - "5432:5432"
