version: '3.9'

services:
  mysql:
    container_name: mysql_fazpay
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: fazpay
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    networks:
      - user-bridge

  api:
    container_name: api_fazpay
    build: .
    restart: always
    ports:
      - "9090:9090"
    networks:
      - user-bridge

networks:
  user-bridge:
    name: user-bridge